### ISSUE TITLE
we need LEGALS

### ISSUE THREAD

**Issue by CristianVellio** [ISPC-Brokers/ISPC-Brokers#3]
# Necesitamos Lineamientos Legales#

##Basándose en los requerimientos funcionales del proyecto y aplicando la legislación
revisada en la cursada: ##

Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO,
Empleados) y si tendrán un contrato con que cláusulas.
· Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la
Profesión.
· Describir que requerimientos deben cumplir el código programado y las bases de
datos según la legislación vigente
· Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de
software.
· Si un integrante del grupo no realiza el trámite de matriculación, que pena le
corresponde a nivel provincial.
· Si el código es replicado, describir como la Ley de Propiedad Intelectual puede
salvaguardar a ARGBroker.
· Si un integrante del grupo divulga los datos de la base de datos interna, describir
como legalmente deberían accionar los demás.
· Si otro integrante del grupo reutiliza el código para fines personales, describir como legalmente
deberían accionar los demás según la Legislación de la Provincia de Córdoba y el
Código Penal Argentino.
· Si otro integrante del grupo reutiliza el código para fines personales a nivel
internacional, describir qué instrumento legal respalda a ARGBroker.
· Si la base de datos es adulterada de manera externa, a nivel nacional, describir qué
instrumento legal respalda a ARGBroker.
· Si los datos de la base de datos son adulterados de manera externa, a nivel
internacional, describir qué instrumento legal respalda a ARGBroker.
· Cuando los programadores de ARGBroker incurren en una negligencia, a que
instrumento legal se acude y quien.
· Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos
Personales.
· Si el cliente decide reemplazar a ARGBroker por otro proveedor, describir cómo se
debe actuar de manera ética ante el cliente y los colegas.
· Si un usuario denuncia a ARGBroker por divulgación de sus datos personales, a que
legislación recurrió el mismo y como ARGBroker puede respaldarse jurídicamente.

**Comment by pauupepper** [comment]
SUBIDO A LA WIKI
